name: C++ CI Workflow

on:
  push:
  pull_request:
  schedule:
  # * is a special character in YAML so you have to quote this string
  # Execute a "nightly" build at 2 AM UTC
  - cron:  '0 2 * * *'


jobs:
  build:
    name: '[${{ matrix.os }}@${{ matrix.build_type }}]'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        os: [ubuntu-20.04, macos-latest, windows-latest]
        exclude:
        # excludes windows-latest Debug build
        # workaround for https://github.com/traversaro/drake-lite-cmake/issues/7
        - os: windows-latest
          build_type: Debug

    steps:
    - uses: actions/checkout@master

    # Print environment variables to simplify development and debugging
    - name: Environment Variables
      shell: bash
      run: env

    # Remove apt repos that are known to break from time to time
    # See https://github.com/actions/virtual-environments/issues/323
    - name: Remove broken apt repos [Ubuntu]
      if:  contains(matrix.os, 'ubuntu')
      run: |
        for apt_file in `grep -lr microsoft /etc/apt/sources.list.d/`; do sudo rm $apt_file; done

    # symlinks disabled are the default setting on Windows, but unfortunatly GitHub Actions enabled them 
    # See: 
    # * https://github.com/robotology/robotology-superbuild/issues/429
    # * https://github.com/actions/virtual-environments/pull/1186  
    - name: Disable Git symlinks on Windows 
      if: contains(matrix.os, 'windows')
      run: git config --global core.symlinks false

    # ============
    # DEPENDENCIES
    # ============

    - name: Dependencies [Windows]
      if: contains(matrix.os, 'windows')
      run: |
        vcpkg.exe --triplet x64-windows install fmt spdlog tinyxml2 eigen3 ccd octomap sdformat9

    - name: Dependencies [macOS]
      if: contains(matrix.os, 'macos')
      run: |
        brew install fmt spdlog eigen tinyxml2 osrf/simulation/sdformat9 libccd octomap

    - name: Dependencies [Ubuntu]
      if: contains(matrix.os, 'ubuntu') 
      run: |
        sudo apt-get update
        sudo apt-get install git build-essential cmake  libeigen3-dev libfmt-dev libspdlog-dev libtinyxml2-dev libccd-dev liboctomap-dev
        # sdformat
        sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-latest.list'
        wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install libsdformat9-dev

    # ===================
    # CMAKE-BASED PROJECT
    # ===================

    - name: Configure [Windows]
      # Use bash also on Windows (otherwise cd, mkdir, ... do not work)
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -A x64 -T ClangCl -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING:BOOL=ON -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install \
                     -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install ..

    - name: Configure [Ubuntu/macOS]
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash
      run: |
        mkdir -p build
        cd build
        cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -DBUILD_TESTING:BOOL=ON -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/install ..

    - name: Build
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}

    - name: Test [Ubuntu/macOS] 
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }} .

    - name: Test [Windows]
      if: contains(matrix.os, 'windows') 
      shell: bash
      run: |
        cd build
        # We need to add to the path the location of manually installed binaries
        export PATH=$PATH:${GITHUB_WORKSPACE}/install/bin
        ctest --output-on-failure -C ${{ matrix.build_type }} .

    - name: Install [Windows]
      if: contains(matrix.os, 'windows') 
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target INSTALL

    - name: Install [Ubuntu/macOS]
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} --target install

    - name: Compile Examples [Windows]
      if: contains(matrix.os, 'windows')
      shell: bash
      run: |
        cd examples
        mkdir -p build
        cd build
        cmake -A x64 -T ClangCl -DCMAKE_TOOLCHAIN_FILE=${VCPKG_INSTALLATION_ROOT}/scripts/buildsystems/vcpkg.cmake \
               -Ddrake_SOURCE_DIR=${GITHUB_WORKSPACE}/build/drake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install ..
        cmake --build . --config ${{ matrix.build_type }}

    - name: Compile Examples [Ubuntu/macOS]
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash
      run: |
        cd examples
        mkdir -p build
        cd build
        cmake -DCMAKE_PREFIX_PATH=${GITHUB_WORKSPACE}/install -Ddrake_SOURCE_DIR=${GITHUB_WORKSPACE}/build/drake ..
        cmake --build . --config ${{ matrix.build_type }}
